Add controllers
PetrutikSA/java-shareit pull request #1
Opened 2024-08-12 15:13 UTC by PetrutikSA

ТЗ выполнил, тесты постмана проходят.
Контроллеры booking и itemrequest не заполнял, т.к. в TODO указаны названия других спринтов, как понимаю нужно будет реализовывать потом.
Модели сделал вначале сам, потом посмотрел советы ментора, но не стал добавлять параметр request в Item, а оставил в Request список преддложенных Item. Пользователь может и завести карточку предмета под определенный запрос, но в дальнейшем предлоагать ее другим пользователям, сразу нескольким, а не только одному. Если последующие спринты будут требовать модель как в советах, то потом переделаю, пока оставил так.
Мапперы реализовал через MapStruct.

2024-08-14 13:51 UTC, afomkina requested changes

2024-08-14 13:51 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader("X-Sharer-User-Id") Long userId,
Нужно вынести повторяющийся хэдер в отдельный класс и сделать его публичной константой, чтобы избежать дублирований в других классах. Чтобы быстро поправить все значения, можно воспользоваться горячими клавишами в IDEA: [Ctrl+Shift+R](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html?keymap=primary_windows#replace_search_string_in_project)

2024-08-14 13:51 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +@Mapper
Нужно сделать маппер [компонентом спринга](https://www.baeldung.com/mapstruct#1-modify-the-mapper:~:text=Mapping%20With%20Dependency%20Injection), тогда его можно будет подключать в сервисе через dependency injection, как и другие бины

2024-08-14 13:51 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
🔥

2024-08-14 13:51 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        boolean isDeleted = itemRepository.updateItem(userId, item, itemId);
Точно ли тут нужно обновлять объект?

2024-08-14 13:51 UTC, afomkina commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestMapper.java
> +@Mapper
Нужно сделать компонентом спринга

2024-08-14 13:51 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +    public boolean isEmailAlreadyInUse(String email) {
_Дополнительные оптимизации_
Чтобы проверка почты проходила за [O(1)](https://skillbox.ru/media/code/big-o-notation-chto-eto-takoe-i-kak-eye-poschitat/), нужно завести Set, куда при добавлении нового пользователя мы будем класть его email. Соответственно, перед тем как добавить пользователя, нужно будет посмотреть, есть ли уже в сете подобный email, если есть - то пользователь с таким email уже существует.

Так как поиск и вставка в сете работают в среднем за O(1), то наш алгоритм поиска одинаковых email тоже будет работать в среднем за O(1), а это гораздо быстрее, чем пройтись по всем элементам списка O(n)

2024-08-15 14:05 UTC, PetrutikSA commented
Исправил

2024-08-16 14:00 UTC, afomkina approved these changes

2024-08-18 13:29 UTC, merged