Add bookings
PetrutikSA/java-shareit pull request #2
Opened 2024-08-29 16:01 UTC by PetrutikSA

Тз сделал, тесты проходят.
В compose файле специально не указывал параметр volume, чтобы данные в БД сбрасывались после прекращения работы контейнера, для того чтобы не засорялась база в процессе разработки и тестирования. В конце добавлю данный параметр.

2024-08-30 14:38 UTC, afomkina requested changes
Привет! Получилась отличная работа! Оставила несколько комментариев для саморазвития

2024-08-30 14:38 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +    );
Нужно перенести на 18 строку

2024-08-30 14:38 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            case ALL -> bookings = bookingRepository.findAllByBookerId(userId);
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2024-08-30 14:38 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        switch (state) {
И этот тоже

2024-08-30 14:38 UTC, afomkina commented on src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить индексы, чтобы ускорить поиск:
[статья](https://tproger.ru/articles/indeksy-v-postgresql/)
[видео](https://www.youtube.com/watch?v=DyqtBiDrz3g)

2024-08-30 14:38 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
>      void bookingUpdateToBooking(BookingUpdateDto bookingUpdateDto, @MappingTarget Booking booking);
Метод нигде не используется

2024-09-02 15:57 UTC, PetrutikSA commented
Исправил.
Индексы добавил, кроме таблиц:
users - тк поле email имеет constraint unique то postgres и так сконсультируется с данным ограничением при поиске по email и выдает то же время ответа как и при поиске по id (потестил на 10 млн записей)
comments - тк не спец запросов пока в логике программы

2024-09-03 13:57 UTC, afomkina approved these changes
Получилась отличная цепочка и индексы! Молодец, что разобрался

2024-09-03 16:18 UTC, merged